# FortuneTowers Configuration

main-lobby: null

messages:
  prefix: "&8[&eFortuneTowers&8] "
  no-permission: "&cNa tento prikaz nemas dostatecna opravneni!"
  command-blocked: "&cBhem hry nemuzes pouzivat tento prikaz!"
  arena-created-init: "&aProces vytvareni zahajen. Vyber rohy pomoci pos1 a pos2 a zadej prikaz znovu."
  arena-created-success: "&aArena &e%arena% &abyla uspesne vytvorena a ulozena!"
  arena-removed: "&cArena &e%arena% &abyla smazana."
  arena-remove-confirm: "&cPro potvrzeni smazani areny %arena% napis prikaz znovu do 5 sekund!"
  pos1-set: "&aPrvni bod areny nastaven na: %loc%"
  pos2-set: "&aDruhy bod areny nastaven na: %loc%"
  spawn-added: "&aSpawn point ID &e%id% &abyl pridan do areny &e%arena%&a."
  spawn-removed: "&aSpawn point ID &e%id% &abyl odebran."
  specspawn-set: "&aSpectator spawn pro arenu &e%arena% &abyl uspesne nastaven."
  specspawn-removed: "&cSpectator spawn pro arenu &e%arena% &abyl odebran."
  lobby-set: "&aLobby pro arenu &e%arena% &abylo nastaveno."
  lobby-removed: "&aLobby pro arenu &e%arena% &abylo zruseno."
  mainlobby-set: "&aHlavni lobby serveru bylo uspesne nastaveno!"
  mainlobby-removed: "&cHlavni lobby serveru bylo zruseno."
  interval-set: "&aInterval davani itemu pro arenu &e%arena% &anastaven na &e%sec%s&a."
  aftergame-set: "&aCas po-herniho vyckani pro arenu &e%arena% &anastaven na &e%sec%s&a."
  player-joined: "&aHrac &e%player% &abyl pridat do areny &e%arena%&a."
  player-joined-spec: "&aHrac &e%player% &abyl pridat jako spectator do areny &e%arena%&a."
  player-left: "&cHrac &e%player% &abyl odpojen z areny &e%arena%&a."
  game-started: "&aHra v arene &e%arena% &abyla spustena!"
  game-stopped: "&cHra v arene &e%arena% &abyla zastavena."
  border-warning-title: "&c&lVAROVANI!"
  border-warning-subtitle: "&7Vrat se ihned zpet do areny!"
  death-title: "&c&lSI ZABITY!"
  death-subtitle: "&7Nyni jsi v rezimu divaka."
  winner-title: "&a&lVYHRA!"
  winner-subtitle: "&e%player% &7vyhral hru!"
  player-died-broadcast: "&c&l[!] &e%player% &7zemrel v arene!"
  game-winner-broadcast: "&a&l[!] &e%player% &agravitacne ovladl arenu a vyhrava hru!"
  reloaded: "&aKonfigurace byla uspesne znovu nactena!"

allowed-commands-in-game:
  - "/towers leave"
  - "/msg"

item-blacklist:
  - "OPERATOR_PERSPECTIVE_EGG"
  - "COMMAND_BLOCK"
  - "CHAIN_COMMAND_BLOCK"
  - "REPEAT_COMMAND_BLOCK"
  - "STRUCTURE_BLOCK"
  - "BARRIER"
  - "LIGHT"
  - "ALLAY_SPAWN_EGG"
  - "AXOLOTL_SPAWN_EGG"
  - "BAT_SPAWN_EGG"

permissions-list:
  towers.admin: "Pristup ke vsem prikazum"
  towers.permission.arena.create: "Vytvoreni areny"
  towers.permission.arena.remove: "Smazani areny"
  towers.permission.arena.pos: "Nastaveni bodu areny"
  towers.permission.arena.addspawn: "Pridani spawnu"
  towers.permission.arena.removespawn: "Odebrani spawnu"
  towers.permission.arena.setspecspawn: "Nastaveni spectator spawnu"
  towers.permission.arena.removespecspawn: "Odebrani spectator spawnu"
  towers.permission.arena.setlobby: "Nastaveni lobby"
  towers.permission.arena.removelobby: "Zruseni lobby"
  towers.permission.setmainlobby: "Nastaveni hlavniho lobby"
  towers.permission.removemainlobby: "Zruseni hlavniho lobby"
  towers.permission.arena.interval: "Nastaveni intervalu"
  towers.permission.arena.aftergame: "Nastaveni po-herniho casu"
  towers.permission.join: "Pridani hrace do hry"
  towers.permission.joinspec: "Pridani hrace jako spectatora"
  towers.permission.leave: "Odebrani hrace ze hry"
  towers.permission.start: "Spusteni hry"
  towers.permission.stop: "Zastaveni hry"
  towers.permission.reload: "Reload pluginu"
